# .coveralls.yml configuration
service_name: travis-ci 		# travis-ci or travis-pro
service_job_id: getenv('TRAVIS_JOB_ID')

# src_dir: src
coverage_clover: storage/logs/clover.xml
json_path: storage/logs/coveralls-upload.json